version: "3.9"

services:
  benchmark:
    build:
      context: .
      dockerfile: benchmark/Dockerfile
    command: ./scripts/entrypoint.sh
    restart: no
    volumes:
      - ./benchmark/logs:/app/logs