version: '3.9'

services:
  benchmark-locust:
    image: replication-shop-benchmark:latest
    pull_policy: never
    build:
      context: benchmark
      dockerfile: Dockerfile
    command: --config /conf/locust.conf --csv=/home/locust/stats/${BRANCH:-}/stats --html report${BRANCH_WITH_PREFIX:-}.html --headless
    volumes:
      - ./benchmark/:/home/locust/
      - ./conf/locust:/conf
    ports:
      - "8089:8089"