version: '3.9'

services:
  cassandra-1:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9042:9042"
  cassandra-2:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9043:9042"
  cassandra-3:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9044:9042"