version: "3.9"

services:
  redis-master:
    extends:
      file: docker-compose.redis.yml
      service: redis-master
  redis-slave-1:
    extends:
      file: docker-compose.redis.yml
      service: redis-slave-1
  redis-slave-2:
    extends:
      file: docker-compose.redis.yml
      service: redis-slave-2
  redis-sentinel-1:
    extends:
      file: docker-compose.redis.yml
      service: redis-sentinel-1
    environment:
      - REDIS_MASTER_HOST=0.0.0.0
  redis-sentinel-2:
    extends:
      file: docker-compose.redis.yml
      service: redis-sentinel-2
    environment:
      - REDIS_MASTER_HOST=0.0.0.0
  redis-sentinel-3:
    extends:
      file: docker-compose.redis.yml
      service: redis-sentinel-3
    environment:
      - REDIS_MASTER_HOST=0.0.0.0