version: "3.9"

services:
  benchmark:
    image: replication-shop-benchmark:latest
    build:
      context: .
      dockerfile: benchmark/Dockerfile
    restart: no
    environment:
      - LOG_FILE_PREFIX
      - EXIT_AFTER_TIMEOUT=${EXIT_AFTER_TIMEOUT:-120}
    volumes:
      - ./benchmark/logs:/app/logs