version: '3.9'

services:
  benchmark-locust-master:
    image: replication-shop-benchmark:latest
    hostname: benchmark-locust-master
    pull_policy: never
    build:
      context: benchmark
      dockerfile: Dockerfile
    command: -f /home/locust/locustfiles/locustfile_1.py --master --config /mnt/conf/locust.conf --csv /home/locust/stats/${BRANCH:-}/stats --html report${BRANCH_WITH_PREFIX:-}.html --headless
    volumes:
      - ./benchmark:/home/locust
      - ./conf/locust:/mnt/conf
    ports:
      - "8089:8089"
  benchmark-locust-worker:
    image: replication-shop-benchmark:latest
    pull_policy: never
    build:
      context: benchmark
      dockerfile: Dockerfile
    command: -f /home/locust/locustfiles/locustfile_1.py --worker --master-host benchmark-locust-master
    volumes:
      - ./benchmark:/home/locust
    deploy:
      replicas: 1
