version: "3.9"

services:
  app-1:
    build: .
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      CONFIG_PATH: ./instances.prod.toml
    ports:
      - "8000"
  app-2:
    build: .
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      CONFIG_PATH: ./instances.prod.toml
    ports:
      - "8000"
  nginx:
    image: bitnami/nginx:latest
    restart: always
    volumes:
      - ./conf/nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf:ro
    ports:
      - "80:80"