version: "3.9"

services:
  benchmark:
    build:
      context: .
      dockerfile: benchmark/Dockerfile
    command: dotnet run ShopClient.dll --config nginx_config.prod.json --log load_test_logs.csv