[[pgpool_instance]]
ip = "localhost"
port = 6432

[[pgpool_instance]]
ip = "localhost"
port = 6433

[[redis_sentinel_instance]]
master_name = "mymaster"
sentinel_addrs = ["localhost:26379", "localhost:26380", "localhost:26381"]

[[cassandra_instance]]
ip = "localhost"
port = 9042

[[cassandra_instance]]
ip = "localhost"
port = 9043

[[cassandra_instance]]
ip = "localhost"
port = 9044
